[[processes]]
name = "Common: tsc"
command = ["npm", "run", "build-watch"]
working_directory = "common"
type = "tsc-watch"

[[processes]]
name = "Common: eslint"
command = ["npm", "run", "check:eslint"]
working_directory = "common"
after = "Common: tsc"

[[processes]]
name = "Client: simple-sync"
command = ["npm", "start"]
working_directory = "client"

[[processes]]
name = "Client: Cosmos"
command = ["npm", "run", "cosmos"]
working_directory = "client"

[[processes]]
name = "Client: Build"
command = ["npm", "run", "build-watch"]
working_directory = "client"
error_regex = "Build finished with ([0-9]+) errors"

[[processes]]
name = "Client: tsc"
command = ["npm", "run", "check:tsc", "--", "--watch"]
working_directory = "client"
type = "tsc-watch"

[[processes]]
name = "Client: eslint"
command = ["npm", "run", "check:eslint"]
working_directory = "client"
after = "Client: tsc"

[[processes]]
name = "Server: Build"
command = ["npm", "run", "build-watch"]
working_directory = "server"
type = "tsc-watch"

[[processes]]
name = "Server: eslint"
command = ["npm", "run", "check:eslint"]
working_directory = "server"
after = "Server: Build"

[[processes]]
name = "Server: Run"
command = ["npm", "run", "start"]
working_directory = "server"
after = "Server: Build"
