[[processes]]
name = "Server"
command = ["npm", "start"]

[[processes]]
name = "Cosmos"
command = ["npm", "run", "cosmos"]

[[processes]]
name = "Build"
command = ["npm", "run", "build-watch"]

[[processes]]
name = "tsc"
command = ["npm", "run", "check:tsc", "--", "--watch"]
type = "tsc-watch"

[[processes]]
name = "eslint"
command = ["npm", "run", "check:eslint"]
after = "tsc"
