/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Category {
  createdAt: Timestamp;
  id: string;
  name: string;
}

export interface DB {
  categories: Category;
}
