/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Card {
  categoryId: string;
  createdAt: Timestamp;
  id: string;
  index: number;
  isSubboardRoot: boolean;
  number: number;
  parentCardId: string | null;
  projectId: string;
  status: string;
  text: string;
}

export interface Category {
  createdAt: Timestamp;
  id: string;
  index: number;
  name: string;
  presetColorId: string;
  projectId: string;
}

export interface Comment {
  cardId: string;
  createdAt: Timestamp;
  id: string;
  text: string;
}

export interface EffectLog {
  effect: Json;
  id: string;
  index: number;
}

export interface Project {
  id: string;
  name: string;
}

export interface User {
  emailAddress: string;
  id: string;
  passwordHash: string;
  passwordSalt: string;
}

export interface DB {
  cards: Card;
  categories: Category;
  comments: Comment;
  effectLog: EffectLog;
  projects: Project;
  users: User;
}
